### ISSUE TITLE
Project Ozone 3 Kappa Mode

### ISSUE THREAD

**Issue by NeosGhost** [TrackStar117/TrackStar117#1]
> # Use the search function before reporting to see if the issue has been reported before.
> **Pack Version:3.2.51**
> **Pack Mode:Kappa**
> **Singleplayer, Multiplayer, or LAN?:**
> Single player
> **Description:**
> There is no recipe for electrotine alloy in the immersive engineering arc furnace. Unlike the red alloy. Making only the more expensive version of electrotine automate-able
> **Steps to reproduce:**
> Search electrotine in Jedi
> **Crash log (use pastebin or issue will be closed):**

looks like immersive engineering added the recipe for red alloy after seeing that projectRed is installed. The recipe for the electrotine alloy in the kiln was added for in the ContentTweaker script...so being able to craft red alloy in the arc furnace may not have been intended. If you wish to have a recipe for the arc furnace send me a reply and I'll send you the two lines you need for the script.

Cheers

**Comment by TrackStar117** [comment]
Dear NeosGhost,

That would be very much appreciated!!

Sincerely,
TrackStar117

**Comment by NeosGhost** [comment]
~\Project Ozone 3 A New Way Forward\scripts\kappa folder

kappa_immersive.zs file
add lines 

mods.immersiveengineering.ArcFurnace.addRecipe(<projectred-core:resource_item:104>, <ore:ingotCopper>, null , 100, 512, [<projectred-core:resource_item:105> * 4], "Alloying");
mods.immersiveengineering.ArcFurnace.addRecipe(<projectred-core:resource_item:104>, <ore:dustCopper>, null , 100, 512, [<projectred-core:resource_item:105> * 4], "Alloying");

and then save it and reload the scripts by restarting the pack

**Comment by TrackStar117** [comment]
Dear NeosGhost,

Thank you very much!!
